/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncsu.monopoly.gui;

import edu.ncsu.monopoly.GameBoard;
import edu.ncsu.monopoly.GameMaster;
import edu.ncsu.monopoly.Player;
import edu.ncsu.monopoly.test.boardScenarios.GameBoardFull;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class GameSetUp extends javax.swing.JFrame {

    private final JFrame parent;
    private int numberOfPlayers;
    private int playerNumber;
    private ArrayList<String> players;
    private ArrayList<Color> playerColors;

    public GameSetUp(JFrame parent) {
        initComponents();
        this.parent = parent;
        this.playerNumber = 1;
        this.numberOfPlayers = 1;
        players = new ArrayList<>();
        playerColors = new ArrayList<>();
    }

    public void startGame() {
        GameMaster master = GameMaster.instance();
        MainWindow window = new MainWindow();
        GameBoard gameBoard = null;
        gameBoard = new GameBoardFull();
        master.setGameBoard(gameBoard);
        master.setNumberOfPlayers(numberOfPlayers);
        //meto los jugadores
        for (int i = 0; i < numberOfPlayers; i++) {
            Player player = master.getPlayer(i);
            player.setName((String)players.get(i));
            player.setPlayerColor(playerColors.get(i));
        }
        window.setupGameBoard(gameBoard);
        window.show();
        master.setGUI(window);
        master.startGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameSetUp = new javax.swing.JLabel();
        lblNumPlayers = new javax.swing.JLabel();
        cmbBxNumPlayers = new javax.swing.JComboBox();
        lblPlayerName = new javax.swing.JLabel();
        txtFldPlayerName = new javax.swing.JTextField();
        lblPlayerInfo = new javax.swing.JLabel();
        btnInputInfo = new javax.swing.JButton();
        lblPlayerColor = new javax.swing.JLabel();
        cmbBxPlayerColor = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblGameSetUp.setText("GAME SETUP");

        lblNumPlayers.setText("Number of Players:");

        cmbBxNumPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbBxNumPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBxNumPlayersMouseClicked(evt);
            }
        });
        cmbBxNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxNumPlayersActionPerformed(evt);
            }
        });

        lblPlayerName.setText("Player Name: ");

        lblPlayerInfo.setText("Player 1 Info");

        btnInputInfo.setText("OK");
        btnInputInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputInfoMouseClicked(evt);
            }
        });

        lblPlayerColor.setText("Player Color:");

        cmbBxPlayerColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnInputInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(cmbBxPlayerColor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(lblGameSetUp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lblNumPlayers)
                                .addGap(34, 34, 34)
                                .addComponent(cmbBxNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPlayerColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlayerInfo)
                                    .addComponent(txtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGameSetUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPlayers)
                    .addComponent(cmbBxNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPlayerInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayerName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerColor)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputInfo)
                    .addComponent(cmbBxPlayerColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setVisible(true);
        this.parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void cmbBxNumPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBxNumPlayersMouseClicked

    }//GEN-LAST:event_cmbBxNumPlayersMouseClicked

    private void btnInputInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputInfoMouseClicked
        String name = txtFldPlayerName.getText();
        players.add(name);
        if (playerNumber == numberOfPlayers) {
            //mandar a empezar el juego
            startGame();
        } else {
            playerNumber++;
            lblPlayerInfo.setText("Player " + playerNumber + " Info");
        }
    }//GEN-LAST:event_btnInputInfoMouseClicked

    private void cmbBxNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxNumPlayersActionPerformed
        lblPlayerInfo.setText("Player 1 info");
        playerNumber = 1;
        numberOfPlayers = Integer.parseInt((String)cmbBxNumPlayers.getSelectedItem());
    }//GEN-LAST:event_cmbBxNumPlayersActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Color color = JColorChooser.showDialog(null, "Choose a color", Color.yellow);
        playerColors.add(color);
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputInfo;
    private javax.swing.JComboBox cmbBxNumPlayers;
    private javax.swing.JComboBox cmbBxPlayerColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblGameSetUp;
    private javax.swing.JLabel lblNumPlayers;
    private javax.swing.JLabel lblPlayerColor;
    private javax.swing.JLabel lblPlayerInfo;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JTextField txtFldPlayerName;
    // End of variables declaration//GEN-END:variables
}
