/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncsu.monopoly.gui;

import edu.ncsu.monopoly.GameBoard;
import edu.ncsu.monopoly.GameMaster;
import edu.ncsu.monopoly.Player;
import edu.ncsu.monopoly.test.boardScenarios.GameBoardFull;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class GameSetUp extends javax.swing.JFrame {

    private final JFrame parent;
    private int numberOfPlayers;
    private int playerNumber;
    private ArrayList<Player> players;
    private Color currentColor;

    public GameSetUp(JFrame parent) {
        initComponents();
        this.parent = parent;
        this.playerNumber = 1;
        this.numberOfPlayers = 1;
        this.players = new ArrayList<>();
        this.currentColor = Color.GREEN;
    }

    public void startGame() {
        //opens game window and starts game
        GameMaster master = GameMaster.instance();
        MainWindow window = new MainWindow();
        GameBoard gameBoard = null;
        gameBoard = new GameBoardFull();
        master.setGameBoard(gameBoard);
        master.setNumberOfPlayers(numberOfPlayers);
        //meto los jugadores
        for (int i = 0; i < numberOfPlayers; i++) {
            Player player = master.getPlayer(i);
            player.setName((String) players.get(i).getName());
            player.setPlayerColor(players.get(i).getPlayerColor());
        }
        window.setupGameBoard(gameBoard);
        window.show();
        master.setGUI(window);
        master.startGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameSetUp = new javax.swing.JLabel();
        lblNumPlayers = new javax.swing.JLabel();
        cmbBxNumPlayers = new javax.swing.JComboBox();
        lblPlayerName = new javax.swing.JLabel();
        txtFldPlayerName = new javax.swing.JTextField();
        lblPlayerInfo = new javax.swing.JLabel();
        btnInputInfo = new javax.swing.JButton();
        btnChooseColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblGameSetUp.setText("GAME SETUP");

        lblNumPlayers.setText("Number of Players:");

        cmbBxNumPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbBxNumPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBxNumPlayersMouseClicked(evt);
            }
        });
        cmbBxNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxNumPlayersActionPerformed(evt);
            }
        });

        lblPlayerName.setText("Player Name: ");

        lblPlayerInfo.setText("Player 1 Info");

        btnInputInfo.setText("OK");
        btnInputInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputInfoMouseClicked(evt);
            }
        });

        btnChooseColor.setText("Choose a Color");
        btnChooseColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnChooseColor)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblGameSetUp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblNumPlayers)
                        .addGap(34, 34, 34)
                        .addComponent(cmbBxNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblPlayerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayerInfo)
                            .addComponent(txtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnInputInfo)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGameSetUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPlayers)
                    .addComponent(cmbBxNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPlayerInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChooseColor)
                .addGap(18, 18, 18)
                .addComponent(btnInputInfo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setVisible(true);
        this.parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void cmbBxNumPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBxNumPlayersMouseClicked

    }//GEN-LAST:event_cmbBxNumPlayersMouseClicked

    private void btnInputInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputInfoMouseClicked
        String name = txtFldPlayerName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name must not be empty");
        } else {
            Player player = new Player();
            player.setName(name);
            player.setPlayerColor(currentColor);
            players.add(player);
            if (playerNumber == numberOfPlayers) {
                startGame();
            } else {
                //input info for next player
                playerNumber++;
                lblPlayerInfo.setText("Player " + playerNumber + " Info");
            }
        }

    }//GEN-LAST:event_btnInputInfoMouseClicked

    private void cmbBxNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxNumPlayersActionPerformed
        lblPlayerInfo.setText("Player 1 info");
        playerNumber = 1;
        numberOfPlayers = Integer.parseInt((String) cmbBxNumPlayers.getSelectedItem());
        players = new ArrayList<>();
    }//GEN-LAST:event_cmbBxNumPlayersActionPerformed

    private void btnChooseColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseColorMouseClicked
        currentColor = JColorChooser.showDialog(null, "Choose a color", Color.yellow);
    }//GEN-LAST:event_btnChooseColorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseColor;
    private javax.swing.JButton btnInputInfo;
    private javax.swing.JComboBox cmbBxNumPlayers;
    private javax.swing.JLabel lblGameSetUp;
    private javax.swing.JLabel lblNumPlayers;
    private javax.swing.JLabel lblPlayerInfo;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JTextField txtFldPlayerName;
    // End of variables declaration//GEN-END:variables
}
